spring.application.name=demo

# Database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/intern_demo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# Connection logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect